openapi: 3.0.0
info:
  title: Teamitaka Swagger API
  version: 1.0.0
  description: Teamitaka 애플리케이션의 Swagger 기반 API 명세서
servers:
  - url: http://localhost:{port}
    variables:
      port:
        default: "10020"
        description: "Server port (dynamic)"
    description: 로컬 개발 서버
paths:
  /:
    get:
      summary: Root Redirect
      description: 루트 경로로 접근 시 /api-docs로 리디렉션합니다.
      responses:
        '302':
          description: Found - 리디렉션됨
          headers:
            Location:
              schema:
                type: string
                example: "/api-docs"
  /hello:
    get:
      summary: Hello World
      description: Returns 'Hello' to the caller
      parameters:
        - name: name
          in: query
          description: The name of the person to whom to say hello
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: "Hello, stranger!"
        default:
          description: Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: "An error occurred"
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT