# api/swagger/swagger.yaml
openapi: 3.0.0
info:
  title: Swagger Practice API
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /:
    get:
      summary: Welcome message
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Welcome to Swagger Practice API! Visit /api-docs for Swagger UI.
  /hello:
    get:
      summary: Hello World message
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Hello, World!