# swagger configuration file (optional, if using swagger-ui-express)

# values in the swagger hash are system configuration for swagger-node
swagger:
  fittingsDirs: [ api/fittings ]  # 유지하거나 제거
  defaultPipe: null
  swaggerControllerPipe: swagger_controllers  # 제거 가능

# bagpipes settings (optional, 제거 추천)
bagpipes:
  _router:
    name: swagger_router
    mockMode: false
    mockControllersDirs: [ api/mocks ]
    controllersDirs: [ api/controllers ]
  _swagger_validate:
    name: swagger_validator
    validateResponse: true
  swagger_controllers:
    - onError: json_error_handler
    - cors
    - swagger_security
    - _swagger_validate
    - express_compatibility
    - _router
  swagger_raw:
    name: swagger_raw